apiVersion: v1
kind: Pod
metadata:
  name: max-pod
  namespace: scb-usra
spec:
  containers:
  - args:
    - echo "hello world"
    command:
    - /bin/bash
    - -c
    image: docker.io/xmkqv/simple:latest
    name: a-container
    resources:
      limits:
        cpu: '1'
        memory: 10Gi
      requests:
        cpu: '1'
        memory: 10Gi
    volumeMounts:
    - mountPath: /scb-usra
      name: scb-usra
  restartPolicy: Never
  volumes:
  - name: scb-usra
    persistentVolumeClaim:
      claimName: scb-usra
