[virtualenvs]
create = true
in-project = true

# cache-dir = "/Users/xmkqv/Library/Caches/pypoetry"
# experimental.new-installer = true
# experimental.system-git-client = false
# installer.max-workers = null
# installer.modern-installation = true
# installer.no-binary = null
# installer.parallel = true
# virtualenvs.create = true

# virtualenvs.in-project = true
# virtualenvs.options.always-copy = false
# virtualenvs.options.no-pip = false
# virtualenvs.options.no-setuptools = false
# virtualenvs.options.system-site-packages = false
# virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/xmkqv/Library/Caches/pypoetry/virtualenvs
# virtualenvs.prefer-active-python = false
# virtualenvs.prompt = "{project_name}-py{python_version}"