name: RAMVID
channels:
  - pytorch
  - conda-forge
  - numba
  - nvidia
  - rapidsai-nightly
  - defaults
dependencies:
  - audioread
  - av
  - blob
  - cusignal
  - datashader
  - ffmpeg
  - flake8
  - flask
  - gitpython
  - ipython
  - ipywidgets
  - jupyterlab
  - librosa
  - matplotlib
  - mpi4py
  - nodejs
  - numba
  - numpy
  - omegaconf
  - openpyxl
  - pandas
  - pep8
  - pillow
  - pip
  - prettytable
  - pynvml
  - python=3.10
  - pytorch=1.13.1
  - pytorch-cuda=11.7
  # - pytorch-lightning=1.9
  - requests
  - resampy
  - rich
  - scipy
  - setuptools
  - tabulate
  - tensorboard
  - tensorflow
  - torchaudio
  - torchvision
  - tqdm
  - visdom
  - xlrd
  - pip:
    - cdpam
    - Cython
    - demucs
    - libtmux
    - museval
    - nvgpu
    - pesq
    - pystoi
    - wavinfo
    - youtube-dl 
    - bert-tensorflow
    - h5py
    - keras
    - mediapipe
    - isort
    - bert-tensorflow
    - mtcnn
    - ffmpeg
    - ffmpeg-python
    - python-ffmpeg
    - retina-face
    - opencv-python