apiVersion: batch/v1
kind: Job
metadata:
  name: ata-data-timeseries
  namespace: scb-usra
spec:
  template:
    spec:
      containers:
      - name: scb-usra
        image: gitlab-registry.nrp-nautilus.io/usra/scb-env-one:latest
        command: ["/bin/bash", "-c"]
        args: [". activate env-es; pip install tqdm; cd /scb-usra/Ata/SubProjects/DataPrep/Codes/; python -u TimeSeriesData.py > output3.log"]
        volumeMounts:
          - mountPath: /scb-usra
            name: scb-usra
        resources:
          limits:
            memory: 4Gi
            cpu: "1"
          requests:
            memory: 4Gi
            cpu: "1"
      volumes:
        - name: scb-usra
          persistentVolumeClaim:
            claimName: scb-usra
      restartPolicy: Never
  backoffLimit: 5