apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRFNE1ESXhOVEExTWpNek9Wb1hEVEk0TURJeE16QTFNak16T1Zvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTZxCm5tNUVSb3FGVHNzWWtJNUExNmZCVTJNbDN6SUpWZnN1dXY3aEpzNk1VMUlCdURuQTJQM0xkaGlpdXFpb0NNamQKRGdwcG92WTVnUVFOZXp1UVo0OGJiQmhac2dWZ1gwK3BUWUlPVjV6ZUo1bGdaclpzWHJsSWZJTHREc3BpcEo0YQpadTRiNnVuVmptSk1LeU4vTHdaRWlvU2d3MXdLRkhlcmF2czA4NHZzQ1F3R2NZNGh4bnhSNzJjdkpjdFFHeHVyCmRnUVNBd2V3U2oycXZWaGJHRzhWU3M3Mms1OU00QlIvMDhrMUxnVmF0alZtYUcvcG9VSnBETTkycVYzTnRwNjcKQUdaRnBNNjhYNHpwSU15NDlDMTNpY0hsZzRGVlNLblNiMUFvWlB0UWUrdGpNMWxTT2FPOWk3U2NxczFzWEdxYwpDazJLUFo3OEUzQUxzMVlpK0swQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFIZ3hmRmwzVkk3eW9Sbzc3M25OOGpEMDhhT1cKQmwxZldORktZQTJhY3ZTZXFsTnk4WGdkaDNMQ3JGVUI0N24vTFlaUVhEeklEVnU5M0RZQ21EbzM1dFZiMXRDMwpUL1BNd202RnpkTW1NY2M3a210dkR2YXhXNDBWbFU5WGptZ214QnhieXd3VTZLUGtCUzVZTjRGZUpEakUvSTVWCll3Ui9HeXJrS2JiL0NYbURrUDNON2orQWEvS1FXcDVPMnA3aUVibFBsTTFrazJ3Q2VVS1NuYTR0MjgvbE1CWEcKRmhNRXA2S3pIYmVXcnJKdGdjbTBLZkRkT25xZm4zbU1rYmpDbk0wV2FiZUN3eEpIWXZnbXR4RkVaTGNhODhGZAppTEF0Rms4UElUTVVXaTg2allXQmFmQkFJRW5mckJaY05mMitVMkF5S0dNN2lBeUMrZWFyQzBBOEJZOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://67.58.53.147:6443
  name: nautilus
contexts:
- context:
    cluster: nautilus
    namespace: scb-usra
    user: http://cilogon.org/serverE/users/49390
  name: nautilus
current-context: nautilus
kind: Config
preferences: {}
users:
- name: http://cilogon.org/serverE/users/49390
  user:
    auth-provider:
      config:
        client-id: myproxy:oa4mp,2012:/client_id/8ebb884b61d21d193edef50ebab11b
        client-secret: 56CPJTJHUMYnnRcXZE18cJJYDOOhKJWVIFtNX4GZNDzHYQCKvz8TynivRBiDfWjZ
        id-token: eyJ0eXAiOiJKV1QiLCJraWQiOiIyNDRCMjM1RjZCMjhFMzQxMDhEMTAxRUFDNzM2MkM0RSIsImFsZyI6IlJTMjU2In0.eyJpc3MiOiJodHRwczovL2NpbG9nb24ub3JnIiwic3ViIjoiaHR0cDovL2NpbG9nb24ub3JnL3NlcnZlckUvdXNlcnMvNDkzOTAiLCJhdWQiOiJteXByb3h5Om9hNG1wLDIwMTI6L2NsaWVudF9pZC84ZWJiODg0YjYxZDIxZDE5M2VkZWY1MGViYWIxMWIiLCJqdGkiOiJodHRwczovL2NpbG9nb24ub3JnL29hdXRoMi9pZFRva2VuLzcxMzQxZmUwYmE2MWMzZDA2MWU1ZDJlYzQ0Y2UzOTY4LzE2NzcxNjE3MDgyNTIiLCJhdXRoX3RpbWUiOjE2NzcxNjA4MzMsImV4cCI6MTY3ODcyMjQ0OCwiaWF0IjoxNjc4NzIxNTQ4fQ.V3sWv__TvCoI1LWFwo2iENBDF5dTXZjkJRwjaPpj6_e9fEDGK9UqhelI3o2GvD8-yGCSp6I7lkcAAo-YhmLkqtL_naUQi2P3mZXZ8RI7smDznLYVX31_0V9LSt0r1hAW1B2gCmEOzWSJmKkiRjbBQKc_At2xVR8f1qUM8KfWrl6g1o1EnQmMzU4nR3KDqt8QSBZz-bKslifYyvk8baKg-e8iTEf-Dm8gNx_ZW4NMyFoeZhFPNwiZ613u0F15I9j3eVci5tMlMgZur_05W9TjHN0vOdTo9WTou2OZdBwb3aYwWHZp0BPSxjBtnwIlv6XJO59UuCAOzEz1ddD15d0ukQ
        idp-issuer-url: https://cilogon.org
        refresh-token: NB2HI4DTHIXS6Y3JNRXWO33OFZXXEZZPN5QXK5DIGIXTEN3FMZTDGMJYGA4GMOBZMZSDOMBSHBRDIYZYGM2WINDFGMZGMNJ7OR4XAZJ5OJSWM4TFONUFI33LMVXCM5DTHUYTMNZYG4ZDCNJUHAYDSNZGOZSXE43JN5XD25RSFYYCM3DJMZSXI2LNMU6TENJZGIYDAMBQGAYA
      name: oidc
