apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-xmkqv
  namespace: scb-usra
spec:
  containers:
  - args:
    - pip install tqdm; sleep infinity
    command:
    - /bin/bash
    - -c
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/prp:latest
    name: gpu-container
    resources:
      limits:
        nvidia.com/gpu: "1"
        cpu: "1"
        memory: 10Gi
    volumeMounts:
    - mountPath: /scb-usra
      name: scb-usra
  restartPolicy: Never
  volumes:
  - name: scb-usra
    persistentVolumeClaim:
      claimName: scb-usra
